### ISSUE TITLE
Crash when looping in a Javascript callback

### ISSUE THREAD

**Issue by mlathan** [hicknhack-software/Twofold-Qt#1]
TwoFold crashes with the following Javascript code. The for-loop in `foo()` is essential for the crash.

``` javascript
function foo(callbackFunc) {
 for(var i = 0; i < 2; ++i) {
  = callbackFunc()
 }
}

= foo(function() { 
 |Crash
})
```

**Comment by arBmind** [comment]
This usage pattern is not allowed.
After any folding expression only a single line of Javascript is allowed. If we would allow this, the visual folding experience would collapse.
